# Generated by Django 5.0.6 on 2026-07-15 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('acción', 'Acción'), ('criptomoneda', 'Criptomoneda'), ('ETF', 'ETF'), ('bono', 'Bono')], max_length=20)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variacion_diaria', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('variacion_semanal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('variacion_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('variacion_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('estadoCivil', models.CharField(choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('separado', 'Separado/a'), ('unión libre', 'Unión Libre')], max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('archivado', 'Archivado')], default='activo', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolios', to='api.cliente')),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolios',
            },
        ),
        migrations.CreateModel(
            name='PrecioHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha', models.DateField()),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_historicos', to='api.activo')),
            ],
            options={
                'verbose_name': 'Precio Histórico',
                'verbose_name_plural': 'Precios Históricos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField()),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(choices=[('Análisis Fundamental', 'Análisis Fundamental'), ('Análisis Técnico', 'Análisis Técnico'), ('Análisis Sectorial', 'Análisis Sectorial'), ('Educativo', 'Educativo'), ('General', 'General')], max_length=50)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('publicado', 'Publicado'), ('despublicado', 'Despublicado')], default='publicado', max_length=15)),
                ('visualizaciones', models.IntegerField(default=0)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='api.administrador')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=8, max_digits=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('completada', 'Completada')], default='completada', max_length=15)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='api.activo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='api.cliente')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='api.portafolio')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('inversionista', 'Inversionista')], max_length=20)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='api.usuario'),
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='api.usuario')),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='administrador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to='api.usuario'),
        ),
        migrations.CreateModel(
            name='PortafolioActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=8, max_digits=20)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolio_activos', to='api.activo')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolio_activos', to='api.portafolio')),
            ],
            options={
                'verbose_name': 'Portafolio Activo',
                'verbose_name_plural': 'Portafolio Activos',
                'unique_together': {('portafolio', 'activo')},
            },
        ),
        migrations.CreateModel(
            name='ReporteActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporte_activos', to='api.activo')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporte_activos', to='api.reporte')),
            ],
            options={
                'verbose_name': 'Reporte Activo',
                'verbose_name_plural': 'Reporte Activos',
                'unique_together': {('reporte', 'activo')},
            },
        ),
    ]
